name: backup
services:
  # Duplicati
  # Backup client that securely stores encrypted, incremental, compressed remote backups of local files on cloud storage services and remote file servers.
  duplicati:
    container_name: duplicati
    image: lscr.io/linuxserver/duplicati:latest
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
      - CLI_ARGS= #optional
    #ports:
      #- 8200:8200
    volumes:
      - ${STACK_DATA}/duplicati:/config
      - ${DUPLICATI_BACKUPS_PATH}:/backups
      - /:/source
    labels:
      # Watchtower add to auto update
      - com.centurylinklabs.watchtower.enable=true
    networks:
     - caddy_net

networks:
  caddy_net:
    external: true
