name: essentials
services:
  # Portainer CE
  # Managing containers via nice web UI
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - 8000:8000 # Agent
      - 9000:9000 # Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STACK_DATA}/portainer/data:/data

  # Watchtower
  # A solution for automating Docker container base image updates
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_WARN_ON_HEAD_FAILURE: 'never'
      WATCHTOWER_NO_STARTUP_MESSAGE: 'true'
      WATCHTOWER_SCHEDULE: '0 0 5 * * 6'
      # WATCHTOWER_NOTIFICATIONS: email
      # WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${EMAIL_SERVER_ADDRESS_FROM} # Remember to set it in .env
      # WATCHTOWER_NOTIFICATION_EMAIL_TO: ${EMAIL_SERVER_ADDRESS_TO} # Remember to set it in .env
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER: ${EMAIL_SERVER} # Remember to set it in .env
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: ${EMAIL_SERVER_PORT} # Remember to set it in .env
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: ${EMAIL_SERVER_AUTH_USER} # Remember to set it in .env
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_AUTH_PASSWORD} # Remember to set it in .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Homarr
  # Fancy dashboard for displaying home services
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${STACK_DATA}/homarr/configs:/app/data/configs
      - ${STACK_DATA}/homarr/icons:/app/public/icons
      - ${STACK_DATA}/homarr/data:/data
    ports:
      - 7575:7575

