version: '3.8'
name: network
services:
  # Pi-hole
  # TODO: DNS add blocker
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - '53:53/tcp' # DNS
      - '53:53/udp' # DNS
      - '67:67/udp' # DHCP
      - '5300:80/tcp' # WEB UI
    environment:
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    volumes:
      - ${DOCKER}/pihole/etc-pihole:/etc/pihole
      - ${DOCKER}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
