name: hass
services:
  # Home Assistant
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${STACK_DATA}/hass/hass-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  # Mosquitto Broker
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "${STACK_DATA}/hass/mosquitto/config:/mosquitto/config"
      - "${STACK_DATA}/hass/mosquitto/data:/mosquitto/data"
      - "${STACK_DATA}/hass/mosquitto/log:/mosquitto/log"
    environment:
      - TZ=${TIMEZONE}
    user: "1883:1883"

